# Generated by Django 3.1.7 on 2022-09-15 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmembers',
            options={'verbose_name': 'Board Member', 'verbose_name_plural': 'Board Members'},
        ),
    ]
